### ISSUE TITLE
"Vagrant up" error

### ISSUE THREAD

**Issue by yuhao0531** [dmc-2016/dmc#5]
Hi
I have reinstalled virtualBox, but it didn't solve the problem. Could you please tell me how can I fix it? Here is what I copy from command promote:

C:\Users\Pietro>cd Documents/GitHub/dmc

C:\Users\Pietro\Documents\GitHub\dmc>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3000 (guest) => 3000 (host) (adapter 1)
    default: 8888 (guest) => 8888 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "0d0dbcf5-94c1-4b6b-b8ef-8697b2aabbba", "--type", "headless
"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (V
ERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

C:\Users\Pietro\Documents\GitHub\dmc>

Best Hao

**Comment by danilnagy** [comment]
As the error suggests, it seems that the problem is VT-x is disabled in your BIOS. Will you try searching for this error in Google? Usually people have similar problems and post solutions on websites such as http://stackoverflow.com/. I did a quick search and found this:

http://stackoverflow.com/questions/33304393/vt-x-is-disabled-in-the-bios-for-both-all-cpu-modes-verr-vmx-msr-all-vmx-disabl

But you might have to search for how to turn on the settings on your particular laptop model. Hope this helps!

**Comment by yuhao0531** [comment]
So I fix the problem by enable the "Intel Virtual Technology: [ENABLED]" of my laptop. You can find it in configuration or security in your bios. Hope this can helps anyone with the same problem.

**Comment by danilnagy** [comment]
Great, I'm glad you were able to resolve it! Thanks for posting about the solution, it will definitely help people confronting similar issues. I'll now mark this issue as closed.
