### ISSUE TITLE
[Errno 20] Not a directory: '-catsdogs/.DS_Store'

### ISSUE THREAD

**Issue by dbm2135** [dmc-2016/dmc#97]
Hi Danil,

I just went to meet with Violet on assignment 5.2 to discuss an error message I've been getting, and she's apparently gotten the same one. Not sure what it means... I have followed all the instructions and not changed any code. 
![screen shot 2016-10-14 at 6 24 02 pm](https://cloud.githubusercontent.com/assets/22079516/19404411/cf276278-923b-11e6-914d-14d2fdd89a46.png)

**Comment by tolaoniyangi** [comment]
I had the same error - fixed it by deleting the .DS_Store file through Terminal. 
You just have to 
- go into the -catsdogs folder (you might have to type ./ before the folder to get in because of the hyphen in the folder name)
- type in: find . -name '.DS_Store' -type f -delete 
- press enter. 
  It should work fine after that
